//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JqueryAjaxDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeId { get; set; }
        [Display(Name = "First Name")]
        [Required(ErrorMessage ="*This field is required")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "*This field is required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "*This field is required")]
        public string Department { get; set; }
        [Display(Name = "Job Type")]
        [Required(ErrorMessage = "*This field is required")]
        public string JobType { get; set; }
        [Required(ErrorMessage = "*This field is required")]
        public decimal Salary { get; set; }
        public int CityId { get; set; }
    }
}
